version: '3'
services:
  web:
    image: boobspics-web
    volumes:
      - ./:/usr/src/autovk
    container_name: autovk
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - VK_GROUP_SAFE_ID=$VK_GROUP_SAFE_ID
      - VK_GROUP_UNSAFE_ID=$VK_GROUP_UNSAFE_ID
      - VK_TOKEN=$VK_GROUP_UNSAFE_ID
    build: .
